// Generated by scripts/build-theme-catalog.mjs.
export const THEME_DEMO_INDEX = Object.freeze([{"slug":"stride","displayName":"Impulso"},{"slug":"classic","displayName":"Clásica"},{"slug":"selecta","displayName":"Selecta"}]);
