#!/usr/bin/env node
// Writes packages/ui/src/icon/ds-icons.ts with the SVG nodes of the Lucide icons
// the Design System uses, read from the installed @lucide/angular. Importing the
// icon components instead would ship one compiled template per icon (~4 kB each).
// Add an icon: map its Design System name to the Lucide component name below and
// run `npm run icons:sync`.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DS_ICONS = {
  home: 'LucideHouse',
  sparkles: 'LucideSparkles',
  message: 'LucideMessageCircle',
  arrowRight: 'LucideArrowRight',
  radio: 'LucideRadio',
  bot: 'LucideBot',
  search: 'LucideSearch',
  alert: 'LucideTriangleAlert',
  check: 'LucideCheck',
  send: 'LucideSend',
  pause: 'LucidePause',
  play: 'LucidePlay',
  list: 'LucideList',
  kanban: 'LucideSquareKanban',
  package: 'LucidePackage',
  upload: 'LucideUpload',
  image: 'LucideImage',
  x: 'LucideX',
  plus: 'LucidePlus',
  book: 'LucideNotebookText',
  rocket: 'LucideRocket',
  shoppingBag: 'LucideShoppingBag',
  chartColumn: 'LucideChartColumn',
  plug: 'LucidePlug',
  creditCard: 'LucideCreditCard',
  settings: 'LucideSettings',
  logOut: 'LucideLogOut',
  circleHelp: 'LucideCircleQuestionMark',
  command: 'LucideCommand',
  minus: 'LucideMinus',
  trash: 'LucideTrash',
  arrowLeft: 'LucideArrowLeft',
  chevronLeft: 'LucideChevronLeft',
  chevronRight: 'LucideChevronRight',
  menu: 'LucideMenu',
  store: 'LucideStore',
  externalLink: 'LucideExternalLink',
  eye: 'LucideEye',
  eyeOff: 'LucideEyeOff',
  mail: 'LucideMail',
  wallet: 'LucideWallet',
  ticket: 'LucideTicket',
  truck: 'LucideTruck',
  fileText: 'LucideFileText',
  lock: 'LucideLock',
  lockKeyhole: 'LucideLockKeyhole',
  chevronUp: 'LucideChevronUp',
  chevronDown: 'LucideChevronDown',
  arrowUp: 'LucideArrowUp',
  shieldCheck: 'LucideShieldCheck',
  circleCheck: 'LucideCircleCheck',
  circleAlert: 'LucideCircleAlert',
  ticketPercent: 'LucideTicketPercent',
  bookOpen: 'LucideBookOpen',
  printer: 'LucidePrinter',
  user: 'LucideUserRound',
  target: 'LucideTarget',
  slidersHorizontal: 'LucideSlidersHorizontal',
  copy: 'LucideCopy',
  info: 'LucideInfo',
  globe: 'LucideGlobe',
  users: 'LucideUsers',
  chartLine: 'LucideChartLine',
  pencil: 'LucidePencil',
  undo: 'LucideUndo2',
  redo: 'LucideRedo2',
  rotateCcw: 'LucideRotateCcw',
  monitor: 'LucideMonitor',
  smartphone: 'LucideSmartphone',
  panelClose: 'LucidePanelRightClose',
  panelOpen: 'LucidePanelRightOpen',
  grip: 'LucideGripVertical',
  layers: 'LucideLayers',
  palette: 'LucidePalette',
  history: 'LucideHistory',
  calendar: 'LucideCalendarDays',
  clock: 'LucideClock',
};

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(join(root, 'packages/ui/package.json'));
const pkgDir = dirname(require.resolve('@lucide/angular/package.json'));
const { version } = JSON.parse(readFileSync(join(pkgDir, 'package.json'), 'utf8'));
const source = readFileSync(join(pkgDir, 'fesm2022/lucide-angular.mjs'), 'utf8');

function iconNode(component) {
  const start = source.indexOf(`class ${component} extends LucideIconBase {`);
  if (start < 0) {
    const alias = source.match(new RegExp(`^const ${component} = (Lucide\\w+);$`, 'm'));
    if (alias) return iconNode(alias[1]);
    throw new Error(`${component} not found in @lucide/angular ${version}`);
  }
  const open = source.indexOf('static icon = ', start) + 'static icon = '.length;
  const close = source.indexOf('\n    };', open) + '\n    }'.length;
  const icon = Function(`"use strict"; return (${source.slice(open, close)});`)();
  return icon.node.map(([tag, attrs]) => {
    const { key: _key, ...rest } = attrs;
    return [tag, rest];
  });
}

const entries = Object.entries(DS_ICONS).map(
  ([name, component]) => `  ${name}: ${JSON.stringify(iconNode(component))},`,
);

const out = `// Generated by scripts/sync-icons.mjs from @lucide/angular ${version} (ISC). Do not edit.
export type DsIconNode = readonly (readonly [string, Readonly<Record<string, string>>])[];

export const DS_ICONS = {
${entries.join('\n')}
} as const satisfies Record<string, DsIconNode>;
`;

writeFileSync(join(root, 'packages/ui/src/icon/ds-icons.ts'), out);
console.log(`Wrote ${entries.length} icons from @lucide/angular ${version}.`);
